version: '3.8'
services:
  dbpostgres:
    image: postgres
    restart: always
    env_file:
      - ".env"
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local